apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: rkg1983
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyYXZpa2FudDE5ODMuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImFtWnliMmN0WTNKbFpEcEpaR1ZoUURFeU13PT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
