apiVersion: v1
kind: Service
metadata:
  name:  rkg1983-rtp-service
  namespace: rkg1983
spec:
  type: NodePort
  selector:
    app: rkg1983-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
